[package]
name = "subclean"
version = "0.2.0"
authors = ["Karel Peeters <karel.peeters.leuven@gmail.com>"]
edition = "2018"

[dependencies]
nom = "7.1.3"
regex = "1.8.4"
itertools = "0.11.0"
failure = { version = "0.1.8", default-features=false, features=["std"] }
glob = "0.3.1"
